
import java.awt.Image;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author Saksham
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author Saksham
 */
public class BUYER_SHOW_PROPERTY_VIEW extends javax.swing.JFrame {

    /**
     * Creates new form BUYER_SHOW_PROPERTY_VIEW
     */
    P_PROPERTY property;
    int buyerid;
    public BUYER_SHOW_PROPERTY_VIEW(int bid,P_PROPERTY prop ) {
        property = prop;
        buyerid = bid;
        initComponents();
        jLabelBHKFill.setText(String.valueOf(prop.getBedrooms()));
        jLabelCityFill.setText(prop.getCity());
        jLabelDescriptionFill.setText(prop.getDescription());
        jLabelFloorFill.setText(String.valueOf(prop.getFloor()));
        jLabelLCFill.setText(prop.getCategory());
        jLabelLocalityFill.setText(prop.getLocality());
        jLabelNameFill.setText(prop.getName());
        //jLabelStateFill.setText(prop.getState());
        jLabelNumberFill.setText(prop.getHouseNo());
        jLabelPostalCodeFill.setText(String.valueOf(prop.getPostalCode()));
        jLabelRERAFill.setText(prop.isRERAString());
        jLabelSizeFill.setText(String.valueOf(prop.getSize()));
        jLabelStateFill.setText(prop.getState());
        jLabelStatusFill.setText(prop.getStatus());
        jLabelStreetNameFill.setText(prop.getStreetName());
        jLabelPriceFill.setText(String.valueOf(prop.getPrice()));
        if(prop.getDuration() != 0){
           jLabelDurationFill.setText(String.valueOf(prop.getDuration()));
        }
        else{
            jLabelDurationFill.setVisible(false);
            jLabelDuration.setVisible(false);
        }
        jLabelRATING.setText(String.valueOf(prop.getRating()));
        jLabelVIEWS.setText(String.valueOf(prop.getViews()));
        
 //adding Images to list
    HashMap<byte[], Integer> imagesListMap = new P_PROPERTY(0).propertyImagesList(prop.getPID());
    DefaultListModel listModel = new DefaultListModel();
    int i = 0;
    for(Integer id: imagesListMap.values())
    {
            listModel.add(i,id);
            i++;    
        }
        jImageListBuyer.setModel(listModel);
}

public ImageIcon resizeImage(String filePath,byte [] byteImage)
    {
        ImageIcon pic;
        if(byteImage!= null) pic = new ImageIcon(byteImage);
        else pic = new ImageIcon(filePath);

        Image img = pic.getImage().getScaledInstance(392, 216,Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img);
        return image;
   }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        rating_button = new javax.swing.JButton();
        agreement_button = new javax.swing.JButton();
        gmap_button = new javax.swing.JButton();
        contact_button = new javax.swing.JButton();
        jLabelName = new javax.swing.JLabel();
        jLabelSize = new javax.swing.JLabel();
        jLabelStatus = new javax.swing.JLabel();
        jLabelNumber = new javax.swing.JLabel();
        jLabelFloor = new javax.swing.JLabel();
        jLabelNameFill = new javax.swing.JLabel();
        jLabelSizeFill = new javax.swing.JLabel();
        jLabelStatusFill = new javax.swing.JLabel();
        jLabelNumberFill = new javax.swing.JLabel();
        jLabelFloorFill = new javax.swing.JLabel();
        jLabelPostalCode = new javax.swing.JLabel();
        jLabelPostalCodeFill = new javax.swing.JLabel();
        jLabelStreetName = new javax.swing.JLabel();
        jLabelStreetNameFill = new javax.swing.JLabel();
        jLabelLocality = new javax.swing.JLabel();
        jLabelLocalityFill = new javax.swing.JLabel();
        jLabelCity = new javax.swing.JLabel();
        jLabelCityFill = new javax.swing.JLabel();
        jLabelState = new javax.swing.JLabel();
        jLabelStateFill = new javax.swing.JLabel();
        jLabelBHKFill = new javax.swing.JLabel();
        jLabelListingCategory = new javax.swing.JLabel();
        jLabelBHK = new javax.swing.JLabel();
        jLabelLCFill = new javax.swing.JLabel();
        jLabelRERA = new javax.swing.JLabel();
        jLabelRERAFill = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabelPhotogograph = new javax.swing.JLabel();
        jLabelDescriptionFill = new javax.swing.JLabel();
        jLabelPrice = new javax.swing.JLabel();
        jLabelPriceFill = new javax.swing.JLabel();
        jLabelDuration = new javax.swing.JLabel();
        jLabelDurationFill = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jImageListBuyer = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabelRATING = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelVIEWS = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 768));

        rating_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rating_button.setText("Rating Review");
        rating_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rating_buttonMouseClicked(evt);
            }
        });
        rating_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rating_buttonActionPerformed(evt);
            }
        });

        agreement_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        agreement_button.setText("GET AGREEMENT");
        agreement_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agreement_buttonMouseClicked(evt);
            }
        });
        agreement_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agreement_buttonActionPerformed(evt);
            }
        });

        gmap_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gmap_button.setText("GET GMAP");
        gmap_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gmap_buttonMouseClicked(evt);
            }
        });
        gmap_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gmap_buttonActionPerformed(evt);
            }
        });

        contact_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        contact_button.setText("CONTACT SELLER");
        contact_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contact_buttonMouseClicked(evt);
            }
        });
        contact_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contact_buttonActionPerformed(evt);
            }
        });

        jLabelName.setBackground(new java.awt.Color(255, 255, 255));
        jLabelName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelName.setText("NAME:");

        jLabelSize.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSize.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelSize.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelSize.setText("SIZE:");

        jLabelStatus.setBackground(new java.awt.Color(255, 255, 255));
        jLabelStatus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelStatus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelStatus.setText("STATUS:");

        jLabelNumber.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNumber.setText("NUMBER:");

        jLabelFloor.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFloor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelFloor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelFloor.setText("FLOOR:");

        jLabelNameFill.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNameFill.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNameFill.setOpaque(true);

        jLabelSizeFill.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSizeFill.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelSizeFill.setOpaque(true);

        jLabelStatusFill.setBackground(new java.awt.Color(255, 255, 255));
        jLabelStatusFill.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelStatusFill.setOpaque(true);

        jLabelNumberFill.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNumberFill.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNumberFill.setOpaque(true);

        jLabelFloorFill.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFloorFill.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelFloorFill.setOpaque(true);

        jLabelPostalCode.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPostalCode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelPostalCode.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPostalCode.setText("POSTAL CODE:");

        jLabelPostalCodeFill.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPostalCodeFill.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelPostalCodeFill.setText(" ");
        jLabelPostalCodeFill.setOpaque(true);

        jLabelStreetName.setBackground(new java.awt.Color(255, 255, 255));
        jLabelStreetName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelStreetName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelStreetName.setText("STREET NAME:");

        jLabelStreetNameFill.setBackground(new java.awt.Color(255, 255, 255));
        jLabelStreetNameFill.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelStreetNameFill.setOpaque(true);

        jLabelLocality.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLocality.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelLocality.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelLocality.setText("LOCALITY:");

        jLabelLocalityFill.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLocalityFill.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelLocalityFill.setOpaque(true);

        jLabelCity.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCity.setText("CITY:");

        jLabelCityFill.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCityFill.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCityFill.setOpaque(true);

        jLabelState.setBackground(new java.awt.Color(255, 255, 255));
        jLabelState.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelState.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelState.setText("STATE:");

        jLabelStateFill.setBackground(new java.awt.Color(255, 255, 255));
        jLabelStateFill.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelStateFill.setOpaque(true);

        jLabelBHKFill.setBackground(new java.awt.Color(255, 255, 255));
        jLabelBHKFill.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelBHKFill.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelBHKFill.setText(" ");
        jLabelBHKFill.setOpaque(true);

        jLabelListingCategory.setBackground(new java.awt.Color(255, 255, 255));
        jLabelListingCategory.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelListingCategory.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelListingCategory.setText("LISTING CATEGORY:");

        jLabelBHK.setBackground(new java.awt.Color(255, 255, 255));
        jLabelBHK.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelBHK.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelBHK.setText("BHK:");

        jLabelLCFill.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLCFill.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelLCFill.setText(" ");
        jLabelLCFill.setOpaque(true);

        jLabelRERA.setBackground(new java.awt.Color(255, 255, 255));
        jLabelRERA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelRERA.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelRERA.setText("RERA APPROVED:");

        jLabelRERAFill.setBackground(new java.awt.Color(255, 255, 255));
        jLabelRERAFill.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelRERAFill.setText(" ");
        jLabelRERAFill.setOpaque(true);

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel29.setText("DESCRIPTION:");

        jLabelPhotogograph.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPhotogograph.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelPhotogograph.setOpaque(true);

        jLabelDescriptionFill.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDescriptionFill.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDescriptionFill.setOpaque(true);

        jLabelPrice.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPrice.setText("PRICE:");

        jLabelPriceFill.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPriceFill.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelPriceFill.setText(" ");
        jLabelPriceFill.setOpaque(true);

        jLabelDuration.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDuration.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelDuration.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDuration.setText("DURATION:");

        jLabelDurationFill.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDurationFill.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelDurationFill.setText(" ");
        jLabelDurationFill.setOpaque(true);

        jImageListBuyer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jImageListBuyerMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jImageListBuyer);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("RATING :");

        jLabelRATING.setBackground(new java.awt.Color(204, 204, 204));
        jLabelRATING.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelRATING.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelRATING.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("VIEWS :");

        jLabelVIEWS.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("IMAGE LIST");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(rating_button, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gmap_button, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(contact_button)
                .addGap(80, 80, 80)
                .addComponent(agreement_button, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelFloor)
                            .addComponent(jLabelNumber))
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSize, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelVIEWS, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelRATING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelPhotogograph, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelNameFill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelSizeFill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelStatusFill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelNumberFill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelFloorFill, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelStreetName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelCity)
                            .addComponent(jLabelLocality, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelState, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelPostalCode))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPostalCodeFill, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelStreetNameFill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelLocalityFill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelCityFill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelStateFill, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelListingCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelBHK, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabelPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelRERA, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelBHKFill, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelLCFill, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelRERAFill, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelDurationFill, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabelPriceFill, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelDescriptionFill, javax.swing.GroupLayout.PREFERRED_SIZE, 843, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelPhotogograph, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRATING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVIEWS, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelRERA, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabelName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                                                .addComponent(jLabelNameFill, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabelSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabelSizeFill, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabelLocality, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabelBHK, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabelListingCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabelStreetNameFill, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabelLocalityFill, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCityFill, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabelStatusFill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelCity, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabelNumberFill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelState, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelStateFill, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelFloorFill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelFloor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelPostalCode)
                                    .addComponent(jLabelDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelPostalCodeFill, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelRERAFill, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelBHKFill, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelLCFill, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(77, 77, 77)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelPriceFill, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelPrice))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelDurationFill, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDescriptionFill, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(rating_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gmap_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(contact_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(agreement_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jImageListBuyerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jImageListBuyerMouseClicked
        // TODO add your handling code here:
        String selectedListItem = String.valueOf(jImageListBuyer.getSelectedValue());
        Integer imageId = Integer.valueOf(selectedListItem);
        byte[] image = new P_PROPERTY(0).getImageById(imageId);
        resizeImage("",image);
        jLabelPhotogograph.setIcon(resizeImage("", image));
                                              
    }//GEN-LAST:event_jImageListBuyerMouseClicked

    private void rating_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rating_buttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rating_buttonMouseClicked

    private void contact_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contact_buttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_contact_buttonMouseClicked

    private void agreement_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agreement_buttonMouseClicked
        // TODO add your handling code here:
        SALE_AGREEMENT_WINDOW swindow;
        RENT_AGREEMENT_WINDOW rwindow;
        System.out.println("in agreement button"+buyerid);
        if(property.getCategory().equalsIgnoreCase("rent")){
           rwindow = new RENT_AGREEMENT_WINDOW(buyerid,property);
           rwindow.setVisible(true);}
        else    {
            swindow = new SALE_AGREEMENT_WINDOW(buyerid,property);
            swindow.setVisible(true);}
    }//GEN-LAST:event_agreement_buttonMouseClicked

    private void gmap_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gmap_buttonActionPerformed
        // TODO add your handling code here:
//        System.out.println("Inside gmap button:"+property.getLatitudeFloat()+ "  "+property.getPID());
        GMap map = new GMap(property.getPID());
        
        map.setVisible(true);
    }//GEN-LAST:event_gmap_buttonActionPerformed

    private void gmap_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gmap_buttonMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_gmap_buttonMouseClicked

    private void rating_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rating_buttonActionPerformed
        // TODO add your handling code here:
        RATING_REVIEW_WINDOW rating_review_window = new RATING_REVIEW_WINDOW(property);
        rating_review_window.setVisible(true);
        rating_review_window.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_rating_buttonActionPerformed

    private void agreement_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agreement_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agreement_buttonActionPerformed

    private void contact_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contact_buttonActionPerformed
        // TODO add your handling code here:
        BUYER_SELLER_DETAILS seller_details= new BUYER_SELLER_DETAILS(property);
        seller_details.setVisible(true);
        seller_details.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_contact_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BUYER_SHOW_PROPERTY_VIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BUYER_SHOW_PROPERTY_VIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BUYER_SHOW_PROPERTY_VIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BUYER_SHOW_PROPERTY_VIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BUYER_SHOW_PROPERTY_VIEW(0,new P_PROPERTY(0)).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agreement_button;
    private javax.swing.JButton contact_button;
    private javax.swing.JButton gmap_button;
    private javax.swing.JList<String> jImageListBuyer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelBHK;
    private javax.swing.JLabel jLabelBHKFill;
    private javax.swing.JLabel jLabelCity;
    private javax.swing.JLabel jLabelCityFill;
    private javax.swing.JLabel jLabelDescriptionFill;
    private javax.swing.JLabel jLabelDuration;
    private javax.swing.JLabel jLabelDurationFill;
    private javax.swing.JLabel jLabelFloor;
    private javax.swing.JLabel jLabelFloorFill;
    private javax.swing.JLabel jLabelLCFill;
    private javax.swing.JLabel jLabelListingCategory;
    private javax.swing.JLabel jLabelLocality;
    private javax.swing.JLabel jLabelLocalityFill;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelNameFill;
    private javax.swing.JLabel jLabelNumber;
    private javax.swing.JLabel jLabelNumberFill;
    private javax.swing.JLabel jLabelPhotogograph;
    private javax.swing.JLabel jLabelPostalCode;
    private javax.swing.JLabel jLabelPostalCodeFill;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JLabel jLabelPriceFill;
    private javax.swing.JLabel jLabelRATING;
    private javax.swing.JLabel jLabelRERA;
    private javax.swing.JLabel jLabelRERAFill;
    private javax.swing.JLabel jLabelSize;
    private javax.swing.JLabel jLabelSizeFill;
    private javax.swing.JLabel jLabelState;
    private javax.swing.JLabel jLabelStateFill;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelStatusFill;
    private javax.swing.JLabel jLabelStreetName;
    private javax.swing.JLabel jLabelStreetNameFill;
    private javax.swing.JLabel jLabelVIEWS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton rating_button;
    // End of variables declaration//GEN-END:variables
}
