/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Mudit
 */
public class LOGIN extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN
     */
    public LOGIN() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        jLabel_Login_Buyer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Login_Buyer.png")));
        jLabel_Login_Seller.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Login_Seller.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_Login_Buyer = new javax.swing.JLabel();
        jLabel_Login_Seller = new javax.swing.JLabel();
        jButton_Login_Buyer = new javax.swing.JButton();
        jButton_Login_Seller = new javax.swing.JButton();
        jButton_Login_Signup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_Login_Buyer.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Login_Buyer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_Login_Buyer.setAlignmentY(0.0F);
        jLabel_Login_Buyer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel_Login_Buyer.setOpaque(true);
        jLabel_Login_Buyer.setPreferredSize(new java.awt.Dimension(512, 512));

        jLabel_Login_Seller.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Login_Seller.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Login_Seller.setAlignmentY(0.0F);
        jLabel_Login_Seller.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel_Login_Seller.setIconTextGap(0);
        jLabel_Login_Seller.setMaximumSize(new java.awt.Dimension(0, 0));
        jLabel_Login_Seller.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel_Login_Seller.setName(""); // NOI18N
        jLabel_Login_Seller.setOpaque(true);
        jLabel_Login_Seller.setPreferredSize(new java.awt.Dimension(512, 512));

        jButton_Login_Buyer.setBackground(new java.awt.Color(255, 204, 153));
        jButton_Login_Buyer.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jButton_Login_Buyer.setText("LOGIN");
        jButton_Login_Buyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Login_BuyerActionPerformed(evt);
            }
        });

        jButton_Login_Seller.setBackground(new java.awt.Color(255, 204, 153));
        jButton_Login_Seller.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jButton_Login_Seller.setText("LOGIN");
        jButton_Login_Seller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Login_SellerActionPerformed(evt);
            }
        });

        jButton_Login_Signup.setBackground(new java.awt.Color(255, 204, 153));
        jButton_Login_Signup.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton_Login_Signup.setText("SIGN UP");
        jButton_Login_Signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Login_SignupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jButton_Login_Buyer, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Login_Seller, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(457, 457, 457)
                .addComponent(jButton_Login_Signup, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(452, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel_Login_Buyer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel_Login_Seller, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel_Login_Buyer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Login_Seller, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Login_Buyer, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Login_Seller, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jButton_Login_Signup, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Login_SellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Login_SellerActionPerformed
        // TODO add your handling code here:
        
        SELLER_LOGIN_WINDOW w1 = new SELLER_LOGIN_WINDOW();
        w1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_Login_SellerActionPerformed

    private void jButton_Login_BuyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Login_BuyerActionPerformed
        // TODO add your handling code here:
        BUYER_LOGIN_WINDOW w2 = new BUYER_LOGIN_WINDOW();
        w2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_Login_BuyerActionPerformed

    private void jButton_Login_SignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Login_SignupActionPerformed
        // TODO add your handling code here:
        SIGN_UP_WINDOW w3 = new SIGN_UP_WINDOW();
        w3.setVisible(true);
    }//GEN-LAST:event_jButton_Login_SignupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Login_Buyer;
    private javax.swing.JButton jButton_Login_Seller;
    private javax.swing.JButton jButton_Login_Signup;
    private javax.swing.JLabel jLabel_Login_Buyer;
    private javax.swing.JLabel jLabel_Login_Seller;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
