


import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Mudit
 */
public class BUYER_DASHBOARD extends javax.swing.JFrame {
int buyerid;
    /**
     * Creates new form BUYER_DASHBOARD
     */

    BUYER_SHOW_PROPERTIES_WINDOW show_window = new BUYER_SHOW_PROPERTIES_WINDOW(buyerid) ;
    BUYER_DASHBOARD_BUY_VS_RENT buy_rent_window = new BUYER_DASHBOARD_BUY_VS_RENT();
    BUYER_DASHBOARD_EMICALCULATOR emi_window = new BUYER_DASHBOARD_EMICALCULATOR();
    public BUYER_DASHBOARD(int bid) {
        buyerid = bid;
        initComponents();
        this.setLocationRelativeTo(null);
        //Icon i = new javax.swing.ImageIcon(getClass().getResource("images/buy.png"));
        //jLabel_Buyer_Dashboard_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("images/buy.png")));
        //jLabel_Buyer_Dashboard_Icon.
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel_Buyer_Dashboard_Icon = new javax.swing.JLabel();
        jLabelShowProperties = new javax.swing.JLabel();
        jLabelEMI = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelBuyRent = new javax.swing.JLabel();
        jPanelSpace = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel_Buyer_Dashboard_Icon.setBackground(new java.awt.Color(204, 255, 255));
        jLabel_Buyer_Dashboard_Icon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jLabel_Buyer_Dashboard_Icon.setOpaque(true);

        jLabelShowProperties.setBackground(new java.awt.Color(255, 204, 153));
        jLabelShowProperties.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelShowProperties.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelShowProperties.setText("Show Properties");
        jLabelShowProperties.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jLabelShowProperties.setOpaque(true);
        jLabelShowProperties.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelShowPropertiesMouseClicked(evt);
            }
        });

        jLabelEMI.setBackground(new java.awt.Color(255, 204, 153));
        jLabelEMI.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelEMI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEMI.setText("EMI Calculator");
        jLabelEMI.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jLabelEMI.setOpaque(true);
        jLabelEMI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEMIMouseClicked(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(204, 255, 255));
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jLabel4.setOpaque(true);

        jLabelBuyRent.setBackground(new java.awt.Color(255, 204, 153));
        jLabelBuyRent.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelBuyRent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBuyRent.setText("Buy vs Rent");
        jLabelBuyRent.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jLabelBuyRent.setOpaque(true);
        jLabelBuyRent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBuyRentMouseClicked(evt);
            }
        });

        jPanelSpace.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelSpaceLayout = new javax.swing.GroupLayout(jPanelSpace);
        jPanelSpace.setLayout(jPanelSpaceLayout);
        jPanelSpaceLayout.setHorizontalGroup(
            jPanelSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 776, Short.MAX_VALUE)
        );
        jPanelSpaceLayout.setVerticalGroup(
            jPanelSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelBuyRent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelEMI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelShowProperties, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Buyer_Dashboard_Icon, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelSpace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel_Buyer_Dashboard_Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelShowProperties, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabelEMI, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabelBuyRent, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanelSpace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelBuyRentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBuyRentMouseClicked
        // TODO add your handling code here:
        if(buy_rent_window!= null)
            buy_rent_window.dispose();
        if(show_window!= null)
            show_window.dispose();
         if(emi_window!=null)
            emi_window.dispose();
        buy_rent_window  = new BUYER_DASHBOARD_BUY_VS_RENT();
        if(show_window!=null)show_window.setVisible(false);
        
        if(emi_window!=null)emi_window.setVisible(false);
        buy_rent_window.setLocationRelativeTo(jPanelSpace);
        if(buy_rent_window!=null)buy_rent_window.setVisible(true);
        //buy_rent_window.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jLabelBuyRentMouseClicked

    private void jLabelShowPropertiesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelShowPropertiesMouseClicked
        // TODO add your handling code here:
        if(show_window!= null)
            show_window.dispose();
        if(buy_rent_window!= null)
            buy_rent_window.dispose();
        if(emi_window!=null)
            emi_window.dispose();
        show_window  = new BUYER_SHOW_PROPERTIES_WINDOW(buyerid);
        if(buy_rent_window!=null)show_window.setVisible(false);
        //if(emi_window!=null)emi_window.setVisible(false);
        show_window.setLocationRelativeTo(jPanelSpace);
        if(show_window!=null)show_window.setVisible(true);
//        show_window.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        //show_window.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jLabelShowPropertiesMouseClicked

    private void jLabelEMIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEMIMouseClicked
        // TODO add your handling code here:
        if(emi_window!=null)
            emi_window.dispose();
        if(show_window!= null)
            show_window.dispose();
        if(buy_rent_window!= null)
            buy_rent_window.dispose();
        emi_window  = new BUYER_DASHBOARD_EMICALCULATOR();
        if(show_window!=null)show_window.setVisible(false);
        
        if(buy_rent_window!=null)buy_rent_window.setVisible(false);
        emi_window.setLocationRelativeTo(jPanelSpace);
        if(emi_window!=null)emi_window.setVisible(true);
    }//GEN-LAST:event_jLabelEMIMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BUYER_DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BUYER_DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BUYER_DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BUYER_DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BUYER_DASHBOARD(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelBuyRent;
    private javax.swing.JLabel jLabelEMI;
    private javax.swing.JLabel jLabelShowProperties;
    private javax.swing.JLabel jLabel_Buyer_Dashboard_Icon;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelSpace;
    // End of variables declaration//GEN-END:variables
}
