
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.border.Border;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Saksham
 */
public class SELLER_DASHBOARD extends javax.swing.JFrame {

    /**
     * Creates new form BUYER_WINDOW
     */
    int sellerid;
    ADD_PROPERTY_SELLER_WINDOW add_window= new ADD_PROPERTY_SELLER_WINDOW(sellerid);
        PROPERTIES_IMAGES_WINDOW images_window  ;
        SHOW_PROPERTIES_WINDOW show_window; 
        EDIT_REMOVE_PROPERTY_SELLER_WINDOW edit_window= new EDIT_REMOVE_PROPERTY_SELLER_WINDOW(sellerid) ;
        public SELLER_DASHBOARD(int sid) {
            
            sellerid = sid;
            add_window = new ADD_PROPERTY_SELLER_WINDOW(sellerid);
//            System.out.println("INSIDE DASHBOARD"+sellerid);
        initComponents();
        
//        
        this.setLocationRelativeTo(null);
        jLabel_seller_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("images/sale.png")));
        
        Border logo_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black) ;
        jLabel_seller_icon.setBorder(logo_border);
        
//        Border seller_name_border = BorderFactory.createMatteBorder(1,1,1,1, Color.white) ;
//        jLabel_seller_name.setBorder(seller_name_border);
        
        Border items_border = BorderFactory.createMatteBorder(0,0,1,0, Color.white) ;
        jLabel_add_properties.setBorder(items_border);
        jLabel_add_images.setBorder(items_border);
        jLabel_view.setBorder(items_border);
        jLabel_edit.setBorder(items_border);
    }
        
//        public SELLER_DASHBOARD() {
//        initComponents();
//        
////        
//        this.setLocationRelativeTo(null);
//        jLabel_seller_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("images/sale.png")));
//        
//        Border logo_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black) ;
//        jLabel_seller_icon.setBorder(logo_border);
        
//        Border seller_name_border = BorderFactory.createMatteBorder(1,1,1,1, Color.white) ;
//        jLabel_seller_name.setBorder(seller_name_border);
        
//        Border items_border = BorderFactory.createMatteBorder(0,0,1,0, Color.white) ;
//        jLabel_add_properties.setBorder(items_border);
//        jLabel_add_images.setBorder(items_border);
//        jLabel_view.setBorder(items_border);
//        jLabel_edit.setBorder(items_border);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_seller_icon = new javax.swing.JLabel();
        jLabel_seller_name = new javax.swing.JLabel();
        jLabel_add_properties = new javax.swing.JLabel();
        jLabel_add_images = new javax.swing.JLabel();
        jLabel_view = new javax.swing.JLabel();
        jLabel_edit = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanelSpace = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jPanel3.setBackground(new java.awt.Color(255, 144, 51));

        jLabel_seller_icon.setBackground(new java.awt.Color(255, 255, 153));
        jLabel_seller_icon.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel_seller_icon.setOpaque(true);

        jLabel_seller_name.setBackground(new java.awt.Color(153, 255, 255));
        jLabel_seller_name.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel_seller_name.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_seller_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_seller_name.setText("SELLER");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel_seller_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_seller_name, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_seller_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_seller_name, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jLabel_add_properties.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel_add_properties.setText("Add Properties");
        jLabel_add_properties.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_add_propertiesMouseClicked(evt);
            }
        });

        jLabel_add_images.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel_add_images.setText("Add Images");
        jLabel_add_images.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_add_imagesMouseClicked(evt);
            }
        });

        jLabel_view.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel_view.setText("View Properties");
        jLabel_view.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_viewMouseClicked(evt);
            }
        });

        jLabel_edit.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel_edit.setText("Edit Properties");
        jLabel_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_editMouseClicked(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 153, 51));
        jButton1.setText("LOG OUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_add_properties, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_add_images, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_view, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel_add_properties, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel_add_images, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel_view, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout jPanelSpaceLayout = new javax.swing.GroupLayout(jPanelSpace);
        jPanelSpace.setLayout(jPanelSpaceLayout);
        jPanelSpaceLayout.setHorizontalGroup(
            jPanelSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
        );
        jPanelSpaceLayout.setVerticalGroup(
            jPanelSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelSpace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelSpace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_add_propertiesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_add_propertiesMouseClicked
        // TODO add your handling code here:
        

//        add_window.setUndecorated(false);

        if(images_window!=null)images_window.setVisible(false);
        if(show_window!=null)show_window.setVisible(false);
        if(edit_window!=null)edit_window.setVisible(false);
        add_window.setLocationRelativeTo(jPanelSpace);
        if(add_window!=null)add_window.setVisible(true);
//        w1.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_jLabel_add_propertiesMouseClicked

    private void jLabel_add_imagesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_add_imagesMouseClicked
        // TODO add your handling code here:
        if(images_window!=null)
            images_window.dispose();
                images_window = new PROPERTIES_IMAGES_WINDOW(sellerid);
//        add_window.setUndecorated(false);
        if(show_window!=null)show_window.setVisible(false);
        if(add_window!=null)add_window.setVisible(false);
        if(edit_window!=null)edit_window.setVisible(false);
        images_window.setLocationRelativeTo(jPanelSpace);
        images_window.setVisible(true);
    }//GEN-LAST:event_jLabel_add_imagesMouseClicked

    private void jLabel_viewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_viewMouseClicked
        // TODO add your handling code here:
        if(show_window!=null)
            show_window.dispose();        
        show_window = new SHOW_PROPERTIES_WINDOW(sellerid);

        if(add_window!=null)add_window.setVisible(false);
        if(images_window!=null)images_window.setVisible(false);
        if(edit_window!=null)edit_window.setVisible(false);
        show_window.setLocationRelativeTo(jPanelSpace);
        if(show_window!=null)show_window.setVisible(true);
    }//GEN-LAST:event_jLabel_viewMouseClicked

    private void jLabel_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_editMouseClicked
        // TODO add your handling code here:
        
        if(edit_window!=null)
            edit_window.dispose();
        edit_window = new EDIT_REMOVE_PROPERTY_SELLER_WINDOW(sellerid);
        if(add_window!=null)add_window.setVisible(false);
        if(images_window!=null)images_window.setVisible(false);
        if(show_window!=null)show_window.setVisible(false);
        edit_window.setLocationRelativeTo(jPanelSpace);
        if(edit_window!=null)edit_window.setVisible(true); 
    }//GEN-LAST:event_jLabel_editMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LOGIN w0 = new LOGIN();
        w0.setVisible(true);
        this.dispose();
        if(add_window!=null)add_window.dispose();
        if(images_window!=null)images_window.dispose();
        if(edit_window!=null)edit_window.dispose();
        if(show_window!=null)show_window.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SELLER_DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SELLER_DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SELLER_DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SELLER_DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SELLER_DASHBOARD(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel_add_images;
    private javax.swing.JLabel jLabel_add_properties;
    private javax.swing.JLabel jLabel_edit;
    private javax.swing.JLabel jLabel_seller_icon;
    private javax.swing.JLabel jLabel_seller_name;
    private javax.swing.JLabel jLabel_view;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelSpace;
    // End of variables declaration//GEN-END:variables
}
